- name: UFW allow valheim tcp ports
  ufw:
    rule: allow
    port: 2456:2458
    proto: tcp
  become: true

- name: UFW allow valheim udp ports
  ufw:
    rule: allow
    port: 2456:2458
    proto: udp
  become: true

- name: Add a new user named {{ valheim_user }}
  user:
    name: "{{ valheim_user }}"
    shell: /bin/bash
  become: true

- name: Directory create
  file: 
    path: "/home/{{ valheim_user }}/valheim"
    state: directory
    owner: "{{ valheim_user }}"
    group: "{{ valheim_user }}"
    mode: 0755
  become: true
  become_user: "{{ valheim_user }}"

- name: Wget linux.gsm 
  ansible.builtin.shell: yes | sudo dpkg --add-architecture i386
  become: true
  args:
    chdir: /home/{{ valheim_user }}/valheim/
    
- name: Wget linux.gsm 
  ansible.builtin.shell: wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh vhserver
  become: true
  become_user: "{{ valheim_user }}"
  args:
    chdir: /home/{{ valheim_user }}/valheim/
  
- name: Vhserver install 
  ansible.builtin.shell: "./vhserver auto-install"
  become: true
  become_user: "{{ valheim_user }}"
  args:
    chdir: /home/{{ valheim_user }}/valheim/
