- name: UFW allow valheim tcp ports
  ufw:
    rule: allow
    port: 2456:2458
    proto: tcp
  become: true

- name: UFW allow valheim udp ports
  ufw:
    rule: allow
    port: 2456:2458
    proto: udp
  become: true

- name: Add a new user named {{ valheim_user }}
  user:
    name: "{{ valheim_user }}"
    shell: /sbin/nologin
  become: true

- name: APT insatll pkg
  apt: 
    name: steamcmd
  become: true

- name: Directory create
  file: 
    path: "/home/{{ valheim_user }}/valheim"
    state: directory
    owner: "{{ valheim_user }}"
    group: "{{ valheim_user }}"
    mode: 0755
  become: true

- name: Download valheim server script
  ansible.builtin.command: steamcmd +login anonymous +force_install_dir ./  +app_update 896660 validate +exit
  become: yes
  become_user: "{{ valheim_user }}"
  args:
    chdir: "/home/{{ valheim_user }}/valheim/"
  become: true